### ISSUE TITLE
Use a newer json schema validation library

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-validation#1]
The json schema library we're using is fairly old, no longer maintained, and is missing some features (eg: `not` validator) from v4. We should upgrade.

Possible targets:

https://github.com/tdegrunt/jsonschema

**Comment by dlongley** [comment]
https://github.com/epoberezkin/ajv

^Recommended by Shane McCarron.

**Comment by mattcollier** [comment]
Switched to `ajv` in v3: https://github.com/digitalbazaar/bedrock-validation/blob/master/CHANGELOG.md#300---2018-02-24

Closing.
