### ISSUE TITLE
FIXME: improve schema and credential context check

### ISSUE THREAD

**Issue by JSAssassin** [digitalbazaar/bedrock-validation#31]
- [ ] TODO: Improve this schema
      Commit: (8ea35cf) Add basic credential schema and test stub.
      Fi[schemas/credential.js:12](https://github.com/digitalbazaar/bedrock-validation/blob/master/schemas/credential.js#L12)
      Matthew Collier commented 6 years ago

- [ ] FIXME: improve credential context check
      Commit: (0e90609) Use jsonldContext to validate Credential @context.
      Fi[schemas/credential.js:18](https://github.com/digitalbazaar/bedrock-validation/blob/master/schemas/credential.js#L18)
      David I. Lehn commented 6 years ago

**Comment by dlongley** [comment]
Closing this as the `credential` schema will be deprecated (see #45).
